import { claims } from './claims'
export type Domain = 'quant' | 'ai' | 'systems' | 'web'
export type Project = {
  slug: string; code: string; name: string; domain: Domain; stack: string; result: string;
  summary: string; problem: string; approach: string; outcome: string; role: string; period: string;
  source?: string; live?: string; package?: string; caseStudy?: boolean;
  decisions: string[]; limitations: string[]; facts: [string, string][];
}
export const projects: Project[] = [
  {
    slug: 'deadbolt', code: 'DBLT', name: 'Deadbolt', domain: 'systems', stack: 'Python, React, AWS', result: 'PUBLIC DEMO',
    summary: 'Access governance dashboard for entitlement drift and auditable remediation.',
    problem: 'Permissions spread across services and teams, making drift difficult to review and decisions hard to trace.',
    approach: 'The system captures entitlement snapshots, applies deterministic risk rules, builds reproducible remediation plans and records reviewer decisions.',
    outcome: 'The public repository documents a hosted, fixture-backed demo and an audit trail. It does not claim a production customer rollout.',
    role: 'Project contributor', period: '2026', source: 'https://github.com/mvrkarthik07/sams_simlplifynext', caseStudy: true,
    decisions: ['Keep risk scoring and authorization in deterministic code.', 'Use the model only for explanations and narrower-scope suggestions.', 'Record plans and decisions so they can be reviewed later.'],
    limitations: ['The hosted demo uses fixtures and a redacted GitHub capture; provider deployment is not established by the public demo.'],
    facts: [['Status', 'Public demo'], ['Review', 'Human approval'], ['Audit', 'Recorded decisions']],
  },
  {
    slug: 'c22-venture', code: 'C22', name: 'C22 veNTUre', domain: 'quant', stack: 'Python, Pandas, Ridge', result: 'RESEARCH SUBMISSION',
    summary: 'Entry-time trading decision model with reproducible backtests and leakage checks.',
    problem: 'Trade selection needs features available before a position resolves and validation that respects time and trader boundaries.',
    approach: 'Causal trader features feed a frozen Ridge model. The repository includes walk-forward splits, leakage audits and a one-command regeneration workflow.',
    outcome: 'The public Stage 3 submission includes a prediction interface, frozen model artifact and reproducible reports.',
    role: 'Research engineer', period: '2026', source: 'https://github.com/mvrkarthik07/c22-venture', caseStudy: true,
    decisions: ['Compute features before each trade outcome is known.', 'Freeze preprocessing and model coefficients for the submission.', 'Keep raw trader data outside the public repository.'],
    limitations: ['The permitted raw trader dataset is not public, so external readers cannot rerun the full analysis from the repository alone.'],
    facts: [['Model', 'Ridge'], ['Validation', 'Walk-forward'], ['Artifact', 'Frozen Stage 3 model']],
  },
  {
    slug: 'tracly', code: 'TRCL', name: 'Tracly', domain: 'web', stack: 'React, TypeScript, Express, Prisma', result: 'MVP',
    summary: 'Offline-friendly personal finance tracker with transactions and weekly reports.',
    problem: 'Recording transactions on a phone should remain usable when the network is unreliable.',
    approach: 'A React PWA stores quick entries locally, retries them with client IDs, and syncs with an Express API backed by Prisma and PostgreSQL.',
    outcome: 'The repository documents transaction, analytics and weekly-report endpoints plus production build instructions.',
    role: 'Project engineer', period: '2026', source: 'https://github.com/mvrkarthik07/tracly', caseStudy: true,
    decisions: ['Queue quick entries in IndexedDB before network sync.', 'Use client IDs to make retries idempotent.', 'Use an httpOnly cookie for the single-user session.'],
    limitations: ['The README describes a single-user product and deployment steps; a public production deployment is not verified.'],
    facts: [['Status', 'MVP'], ['Offline queue', 'IndexedDB'], ['API', 'Express and Prisma']],
  },
  {
    slug: 'coderecon', code: 'CRCN', name: 'CodeRecon', domain: 'ai', stack: 'Python, AST, Ollama', result: 'PUBLISHED ON PYPI',
    summary: 'Local-first code intelligence for structured architecture reviews.',
    problem: 'Architecture reviews need reliable structural evidence without sending a repository to a cloud model.',
    approach: 'A deterministic Python AST layer maps dependencies and complexity hotspots. A local Ollama layer turns those findings into a review.',
    outcome: 'The CLI package is published on PyPI. Repository scale, runtime and download counts have not been verified for publication.',
    role: 'Sole engineer', period: '2026', source: 'https://github.com/mvrkarthik07/coderecon', package: 'https://pypi.org/project/coderecon/', caseStudy: true,
    decisions: ['Use AST parsing for structural signals before model inference.', 'Keep inference local through Ollama.', 'Package the CLI and run checks through GitHub Actions.'],
    limitations: ['No published benchmark for largest repository audited or end-to-end runtime.'],
    facts: [['Release', 'Published on PyPI'], ['Analysis', 'Python AST'], ['Inference', 'Local Ollama']],
  },
  {
    slug: 'archlab', code: 'ARCH-LAB', name: 'ArchLab', domain: 'systems', stack: 'Swift 6, SwiftUI', result: claims.swiftResult.toUpperCase(),
    summary: 'An interactive simulator for software architecture failures and recovery paths.',
    problem: 'Static architecture diagrams make it hard to see how traffic spikes lead to cascading failures.',
    approach: 'A SwiftUI simulation engine models data flow and visualises latency and throughput as architecture choices change.',
    outcome: `Associated with the Apple Swift Student Challenge 2026 ${claims.swiftResult} recognition. A scenario count has not been verified.`,
    role: 'Sole engineer', period: '2026', source: 'https://github.com/mvrkarthik07/ArchLab', caseStudy: true,
    decisions: ['Use a modular engine, state and view structure.', 'Use Swift 6 concurrency for simulation state.', 'Render diagnostic flows with SwiftUI Canvas.'],
    limitations: ['Simulation is educational; it is not a production traffic benchmark.'],
    facts: [['Recognition', claims.swiftResult], ['Platform', 'SwiftUI'], ['Scenarios', 'Not published']],
  },
  {
    slug: 'coverbuddy', code: 'CVB', name: 'CoverBuddy', domain: 'ai', stack: 'React, FastAPI, Supabase', result: 'LIVE',
    summary: 'A structured workflow for evidence-based cover letters.',
    problem: 'A one-shot generator leaves applicants without an editing, saving and export workflow.',
    approach: 'Resume parsing and evidence selection feed drafting; users can edit, save, regenerate and export PDF documents.',
    outcome: 'The web application is live. User and letter counts have not been verified for publication.',
    role: 'Product and engineering lead', period: '2026', live: 'https://covbuddy.netlify.app/', caseStudy: true,
    decisions: ['Separate React frontend and FastAPI backend.', 'Persist applications and drafts with Supabase.', 'Provide a deterministic local fallback when model generation fails.'],
    limitations: ['No verified user or document count.'],
    facts: [['Status', 'Live'], ['Frontend', 'React'], ['Backend', 'FastAPI']],
  },
  {
    slug: 'multi-agent-rl-trading-system', code: 'MARL', name: 'Multi-agent RL trader', domain: 'quant', stack: 'PyTorch, MADDPG, Pandas', result: 'RESEARCH',
    summary: 'A multi-agent trading research system using portfolio-level rewards.',
    problem: 'Portfolio decisions require evaluating multiple assets and costs together.',
    approach: 'The project uses OHLCV features, MADDPG agents and a portfolio reward to study allocation decisions.',
    outcome: 'Karthik reports a 1.32 Sharpe, 30% profit and −7% drawdown. The data period, split, costs and baseline are unavailable, so these are not presented as out-of-sample results.',
    role: 'Researcher and engineer', period: '2026', source: 'https://github.com/mvrkarthik07/marl-trading-system', caseStudy: true,
    decisions: ['Use portfolio-level reward shaping.', 'Define single-agent baselines for future comparison.'],
    limitations: ['Data period, train/validation/test dates, turnover, costs and baseline Sharpe are not verified.', 'Reported metrics cannot be classified as out-of-sample.'],
    facts: [['Status', 'Research'], ['Reported Sharpe', '1.32 (split unverified)'], ['Reported profit', '30%'], ['Reported drawdown', '−7%']],
  },
  {
    slug: 'roleaudit', code: 'RAUD', name: 'RoleAudit', domain: 'web', stack: 'React, JavaScript', result: 'LIVE',
    summary: 'A rule-based resume-to-role analysis tool.',
    problem: 'Opaque fit scores do not explain missing candidate evidence.',
    approach: 'Defined role categories and scoring rules surface strengths, gaps and improvement areas.',
    outcome: 'The web application is live and scores candidate evidence against role criteria.',
    role: 'Product and engineering lead', period: '2026', source: 'https://github.com/mvrkarthik07/RoleAudit', live: 'https://role-audit.vercel.app/', caseStudy: true,
    decisions: ['Use inspectable scoring rules.', 'Show strengths and gaps alongside the aggregate score.'],
    limitations: ['The score is guidance, not an employer hiring decision.'],
    facts: [['Status', 'Live'], ['Method', 'Rule-based scoring']],
  },
  {
    slug: 'conspiracyweb', code: 'CSWB', name: 'ConspiracyWeb SG', domain: 'web', stack: 'React, TypeScript, Next.js', result: 'EDUCATIONAL PROTOTYPE',
    summary: 'Searchable Singapore conspiracy-claim database with topic pages and a quiz.',
    problem: 'Claim collections need clear context and verification language so readers can distinguish a claim from a finding.',
    approach: 'A Vite React interface presents categories, theories and a quiz; a Next.js API provides related article links with fallback sources.',
    outcome: 'The public repository includes the interface, API and seed data as an educational prototype.',
    role: 'Project engineer', period: '2026', source: 'https://github.com/mvrkarthik07/ConspiracyWeb', caseStudy: true,
    decisions: ['Keep claims and verification status explicit in the interface.', 'Use a separate API route for related article search.', 'Keep a demo fallback when search credentials are unavailable.'],
    limitations: ['Seed data and placeholder images are used; search may return Wikipedia or mock results when provider access is unavailable.'],
    facts: [['Status', 'Educational prototype'], ['Frontend', 'React and TypeScript'], ['API', 'Next.js']],
  },
  {
    slug: 'brainx', code: 'BRNX', name: 'BrainX', domain: 'ai', stack: 'FastAPI, SQLite, FAISS, Ollama', result: 'LOCAL PROTOTYPE',
    summary: 'On-device knowledge system combining document search with persistent graph state.',
    problem: 'Personal knowledge retrieval should preserve local control of documents and state.',
    approach: 'A FastAPI backend stores documents, concepts and feedback in SQLite, uses FAISS for vector search, and runs embeddings and generation through Ollama.',
    outcome: 'The repository documents local ingestion, query and feedback flows. A Tauri desktop interface remains planned.',
    role: 'Project engineer', period: '2026', source: 'https://github.com/mvrkarthik07/brainX', caseStudy: true,
    decisions: ['Keep storage and model inference on the user’s device.', 'Use SQLite for persistent graph state.', 'Provide sample scripts for ingestion and query checks.'],
    limitations: ['The desktop interface is a plan in the public README, not a completed release.'],
    facts: [['Status', 'Local prototype'], ['Search', 'FAISS'], ['Inference', 'Ollama']],
  },
  {
    slug: 'heliodesk', code: 'HLIO', name: 'HelioDesk', domain: 'web', stack: 'React, Vite, Supabase', result: 'IN PROGRESS',
    summary: 'Modular career and productivity dashboard for tasks, signals and tools.',
    problem: 'Work scattered across separate tools creates repeated context switching.',
    approach: 'A React dashboard uses a modular widget structure, Supabase authentication and persistent user settings.',
    outcome: 'The public README lists the core layout, authentication and initial widget framework as implemented.',
    role: 'Project engineer', period: '2026', source: 'https://github.com/mvrkarthik07/heliodesk', caseStudy: true,
    decisions: ['Keep widgets independent of the core layout.', 'Separate UI state from authentication and storage.', 'Build around a responsive dashboard.'],
    limitations: ['Calendar, email and user-configurable widgets are listed as roadmap work.'],
    facts: [['Status', 'In progress'], ['Frontend', 'React and Vite'], ['Auth', 'Supabase']],
  },
  {
    slug: 'parklah', code: 'PARK', name: 'ParkLah', domain: 'web', stack: 'React, TypeScript, Express, Prisma', result: 'DRAFT MVP',
    summary: 'Carpark finder prototype with a full-stack structure and API adapter slots.',
    problem: 'Drivers need a simple way to browse carpark options without navigating several disconnected sources.',
    approach: 'A React frontend and Express backend use Prisma for data access, with mock adapters and slots for live integrations.',
    outcome: 'The repository describes an MVP and a public preview is available.',
    role: 'Project engineer', period: '2025', source: 'https://github.com/mvrkarthik07/Parklah', live: 'https://parklah.vercel.app/', caseStudy: true,
    decisions: ['Separate frontend and backend in TypeScript.', 'Use mock adapters while external data integrations are developed.', 'Provide a browser preview for the draft.'],
    limitations: ['The repository labels this as a draft; real API adapters are not documented as complete.'],
    facts: [['Status', 'Draft MVP'], ['Preview', 'Public site'], ['Data', 'Mock adapters']],
  },
  {
    slug: 'xarvyn', code: 'XRVN', name: 'Xarvyn', domain: 'systems', stack: 'AI agents, automation', result: 'IN PROGRESS',
    summary: 'An experiment in agent workflows and structured execution.',
    problem: 'Tool-mediated workflows need clear state and repeatable output.',
    approach: 'Exploring task state and reasoning loops in a research sandbox.',
    outcome: 'In progress. No public result yet.', role: 'Engineer', period: '2026', caseStudy: false,
    decisions: [], limitations: ['No public result or case study yet.'], facts: [['Status', 'In progress']],
  },
]
